name = "agglayer-developer-portal"
main = "_worker.js"
compatibility_date = "2024-07-04"
workers_dev = false

[assets]
binding = "ASSETS"
directory = "./.next"

[env.staging]
routes = [
  { pattern = "builder.staging.agglayer.dev", custom_domain = true }
]

[env.production]
routes = [
  { pattern = "builder.agglayer.dev", custom_domain = true }
]