name: Deploy

on:
  push:
    branches:
      - main
      - staging

# Ensure only one deploy per ref at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  get-env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-env.outputs.env }}
    steps:
      - id: set-env
        shell: bash
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "env=production" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            echo "env=staging" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported branch: ${GITHUB_REF_NAME}"
            exit 1
          fi

  build-and-deploy:
    needs: [get-env]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (clean)
        run: npm ci

      - name: Build
        run: npm run deploy:${{ needs.get-env.outputs.env }}
        env:
          CI: false

      - name: Deploy
        run: npx wrangler deploy --env ${{ needs.get-env.outputs.env }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_WORKER_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_WORKER_API_TOKEN }}